[package]
name = "website_project"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1